services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madonna
    ports:
      - "5432:5432"

  flask:
    restart: always
    build: ./flask
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: flaskr
      FLASK_ENV: development
      DB_PASSWORD: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/madonna
    ports:
      - "5000:5000"
    volumes:
      - ./flask/:/usr/src/app/